version: "3.8"

x-base-deploy-config: &base-deploy-config
    replicas: 2

    update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
        parallelism: 1

    rollback_config:
        order: start-first
        failure_action: pause
        parallelism: 1

services:
    webapp:
        image: lharti/jsonthing-web:0.5.8
        networks:
            - private
        environment:
            - PORT=3000
            - INT_API_URL=http://api:5000
        depends_on:
            - mongo
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
            interval: 10s
            timeout: 5s
            retries: 3
        deploy:
            <<: *base-deploy-config

    api:
        image: lharti/jsonthing-api
        networks:
            - private
        environment:
            - PORT=5000
            - DB_NAME=jsonthing
            - DB_URI=${DB_URI}
        depends_on:
            - mongo
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
            interval: 10s
            timeout: 5s
            retries: 3
        deploy:
            <<: *base-deploy-config

    mongo:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        networks:
            - private
        volumes:
            - mongo-data:/data/db:rw
        deploy:
            replicas: 1

            update_config:
                order: stop-first
                failure_action: rollback
                parallelism: 1

            rollback_config:
                order: stop-first
                failure_action: pause
                parallelism: 1

    nginx:
        image: nginx:latest
        networks:
            - public
            - private
        ports:
            - "80:80"
        configs:
            - source: nginx
              target: /etc/nginx/nginx.conf
        depends_on:
            - webapp
            - api

        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/healthz"]
            interval: 10s
            timeout: 5s
            retries: 3
        deploy:
            <<: *base-deploy-config

configs:
    nginx:
        external: true

volumes:
    mongo-data:

networks:
    public:
        driver: overlay

    private:
        driver: overlay
        internal: true
