name: build-api

on:
    push:
        branches:
            - main
        paths:
            - "apps/jsonthing-api/Dockerfile"
            - "apps/jsonthing-api/**"
    workflow_dispatch:

jobs:
    push-version-tag:
        runs-on: ubuntu-latest
        continue-on-error: true

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up jq
              run: sudo apt-get install -y jq

            - name: Extract version from package.json
              id: get-version
              run: echo "version=$(jq -r .version < apps/jsonthing-api/package.json)" >> $GITHUB_OUTPUT

            - name: Push new versions
              run: |
                  NEW_VERSION=${{ steps.get-version.outputs.version }}
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'
                  git tag "jsonthing-api@${NEW_VERSION}"
                  git push --tags

    unit-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Get pnpm store path
              id: get-pnpm-store
              shell: bash
              run: echo "path=$(pnpm store path)" >> ${GITHUB_OUTPUT}

            - name: Cache pnpm store
              id: cache-pnpm-store
              uses: actions/cache@v4
              with:
                  path: ${{ steps.get-pnpm-store.outputs.path}}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Run tests
              run: pnpm turbo run test --ui=stream --filter jsonthing-api

    build-and-push:
        runs-on: ubuntu-latest
        needs: [unit-tests, push-version-tag]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract version from package.json
              id: get-version
              run: echo "version=$(jq -r .version < apps/jsonthing-api/package.json)" >> $GITHUB_OUTPUT

            - name: Build and push Docker image for API
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: apps/jsonthing-api/Dockerfile
                  push: true
                  tags: |
                      lharti/jsonthing-api:latest
                      lharti/jsonthing-api:${{ steps.get-version.outputs.version }}
